# Generated by Django 4.1.1 on 2022-09-21 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="quntity",
            new_name="quantity",
        ),
    ]
