# Generated by Django 4.1.1 on 2022-09-22 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_alter_payment_date_completed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="order",
            new_name="payment_for",
        ),
    ]
